import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Header";
import ThemeSwitch from "./components/ThemeSwitch";

export const metadata: Metadata = {
    title: "TV search app",
    description:
        "Updated version of a previous React app, generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="">
                <Providers>
                    <main className="max-w-6xl mx-auto">
                        <div className="p-6 w-full flex justify-between items-center gap-4">
                            <Header />

                            <ThemeSwitch />
                        </div>
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
